parameters:
#    kd_facebook.example.class: KD\FacebookBundle\Example

services:
#    kd_facebook.example:
#        class: %kd_facebook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
